{{- if .Values.serviceAccounts.spark.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "livy.sparkServiceAccountName" . }}
  {{- if .Values.ownerReference.overRide }}
  {{- with  .Values.ownerReference.ownerReferences }}
  ownerReferences: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "livy.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.spark.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
